export enum KEY_SETTING {
  ENABLE_ACTIVE_CODE = 'ENABLE_ACTIVE_CODE',
  DELAY_FOR_NEXT_TRACKING_IN_MINUTES = 'DELAY_FOR_NEXT_TRACKING_IN_MINUTES',
  SLEEP_TRACKING_MAX_EARN_PER_DAY = 'SLEEP_TRACKING_MAX_EARN_PER_DAY',
}

export enum KEY_VALUE_ACTIVE_CODE_SETTING {
  ACTIVE = 'true',
  INACTIVE = 'false'
}
