export const DEFAULT_COST_OPEN_GACHA = {
  NORMAL_GACHA_SINGLE: 24,
  NORMAL_GACHA_MULTIPLE: 200,
  SPECIAL_GACHA_SINGLE: 240,
  SPECIAL_GACHA_MULTIPLE: 2000,
};

export const COST_OPEN_GACHA = {
  1: 'NORMAL_GACHA_SINGLE',
  2: 'NORMAL_GACHA_MULTIPLE',
  3: 'SPECIAL_GACHA_SINGLE',
  4: 'SPECIAL_GACHA_MULTIPLE',
};

export const PROBABILITY_GACHA = {
  NORMAL_GACHA_SINGLE: 1,
  NORMAL_GACHA_MULTIPLE: 2,
  SPECIAL_GACHA_SINGLE: 3,
  SPECIAL_GACHA_MULTIPLE: 4,
  NORMAL_FREE: 5,
  SPECIAL_FREE: 6,
};

export const SYMBOL_TOKEN = {
  SLFT: 'slft',
  AVAX: 'avax',
  SLGT: 'slgt',
};

export const PROBABILITY_NORMAL_GACHA_RESULT = {
  COMMON_BED: 'COMMON_BED',
  UNCOMMON_BED: 'UNCOMMON_BED',
  JEWEL_LEVEL_1: 'JEWEL_LEVEL_1',
  JEWEL_LEVEL_2: 'JEWEL_LEVEL_2',
  ITEM_LEVEL_1: 'ITEM_LEVEL_1',
  ITEM_LEVEL_2: 'ITEM_LEVEL_2',
};

export const PROBABILITY_SPECIAL_GACHA_RESULT = {
  COMMON_BED: 'COMMON_BED',
  UNCOMMON_BED: 'UNCOMMON_BED',
  JEWEL_LEVEL_1: 'JEWEL_LEVEL_1',
  JEWEL_LEVEL_2: 'JEWEL_LEVEL_2',
  ITEM_LEVEL_1: 'ITEM_LEVEL_1',
  ITEM_LEVEL_2: 'ITEM_LEVEL_2',
};

export const PROBABILITY_CONFIG_KEY = {
  COMMON: 'COMMON',
  SPECIAL: 'SPECIAL',
};

export const GACHA_CONFIG_KEY = {
  COMMON_RESET_TIME: 'COMMON_RESET_TIME',
  SPECIAL_RESET_TIME: 'SPECIAL_RESET_TIME',
  COST_OPEN_GACHA: 'COST_OPEN_GACHA',
  NORMAL_GACHA_MAIN_NET: 'NORMAL_GACHA_MAIN_NET',
  SPECIAL_GACHA_MAIN_NET: 'SPECIAL_GACHA_MAIN_NET',
  NORMAL_GACHA_TEST_NET: 'NORMAL_GACHA_TEST_NET',
  SPECIAL_GACHA_TEST_NET: 'SPECIAL_GACHA_TEST_NET',
  COMMON_BED_NORMAL_MAIN_NET: 'COMMON_BED_NORMAL_MAIN_NET',
  UNCOMMON_BED_NORMAL_MAIN_NET: 'UNCOMMON_BED_NORMAL_MAIN_NET',
  COMMON_BED_CLASS_NFT: 'COMMON_BED_CLASS_NFT',
  PRO_NORMAL_TEST_NET: 'PRO_NORMAL_TEST_NET',
  PRO_SPECIAL_TEST_NET: 'PRO_SPECIAL_TEST_NET',
  PRO_NORMAL_MAIN_NET: 'PRO_NORMAL_MAIN_NET',
  PRO_SPECIAL_MAIN_NET: 'PRO_SPECIAL_MAIN_NET',
  COMMON: 'COMMON',
  SPECIAL: 'SPECIAL',
};

export const SPECIAL_RESET_TIME = 100;
export const COMMON_RESET_TIME = 100;

export const NFT_TYPE_BY_CATEGORY = {
  1: 'bed',
  2: 'jewel',
  3: 'item',
};

export const GACHA_TYPE = {
  1: 'NORMAL_GACHA_SINGLE',
  2: 'NORMAL_GACHA_MULTIPLE',
  3: 'SPECIAL_GACHA_SINGLE',
  4: 'SPECIAL_GACHA_MULTIPLE',
  5: 'NORMAL_GET',
  6: 'SPECIAL_GET',
};
