export const MESSAGE = {
  balance_not_enough: 'balance_not_enough',
  nft_not_found: 'nft_not_found',
  nft_can_not_sell: 'nft_can_not_sell',
  bed_has_jewels: 'bed_has_jewels',
  sell_success: 'sell_success',
  invalid_nft: 'invalid_nft',
  can_not_upgrade: 'can not upgrade',
  upgrade_success: 'upgrade_success',
  upgrade_fail: 'upgrade_fail',
  bed_is_still_good: 'bed_is_still_good',
  durability_is_better: 'durability_is_better',
  bed_not_found: 'bed_not_found',
  level_is_highest: 'level_is_highest',
  cost_is_not_correct: 'cost_is_not_correct',
  can_not_get_fee: 'can_not_get_fee',
  can_not_get_percent_minting: 'can_not_get_percent_minting',
  can_not_get_random_quality: 'can_not_get_random_quality',
  can_not_get_broken_rate: 'can_not_get_broken_rate',
  bed_enough_times_mint: 'bed_enough_times_mint',
  mint_success: 'mint_success',
  mint_fail: 'mint_fail',
  cancel_sell_success: 'cancel_sell_success',
  do_not_buy_your_nft: 'do_not_buy_your_nft',
  not_owner_nft: 'not_owner_nft',
  no_items_found_or_items_used_for_another_bed: 'no_items_found_or_items_used_for_another_bed',
  you_do_not_own_this_nft: 'you_do_not_own_this_nft',
  sleeping_bed: 'sleeping_bed',
  you_have_no_gems_to_assign: 'you_have_no_gems_to_assign',
  nft_not_found_or_jewel_is_used: 'nft_not_found_or_jewel_is_used',
  no_socket_to_add_jewel: 'no_socket_to_add_jewel',
  the_bed_has_not_been_opened_socket: 'the_bed_has_not_been_opened_socket',
  no_more_socket_to_assign_jewel: 'no_more_socket_to_assign_jewel',
  no_jewel_to_remove: 'no_jewel_to_remove',
  do_not_own_the_bedbox: 'you_do_not_own_the_bedbox_or_the_bedbox_does_not_currently_exist',
  not_random_quality: 'not_random_quality',
  failed_to_open_bedbox: 'failed_to_open_bedbox',
  the_bed_has_been_added_item: 'The_bed_has_been_added_item',
  minting_not_exists: 'minting_not_exists',
  not_spending_balance: 'not_spending_balance',
  nft_can_not_withdraw: 'nft_can_not_withdraw',
  sell_error: 'Selling price must be greater than 0'
}
